title SteavenLinux (Linux Cachyos Lts)
linux /vmlinuz-linux-cachyos-lts
initrd /amd-ucode.img
initrd /initramfs-linux-cachyos-lts.img
options root=UUID=72fc446c-0b05-491d-9b02-969cb75fc03a rw quiet splash resume=UUID=72fc446c-0b05-491d-9b02-969cb75fc03a resume_offset=10438656 iommu=pt pcie_acs_override=downstream,multifunction pcie_port_pm=off split_lock_detect=off intel_iommu=on usbcore.autosuspend=-1

# vfio-pci.ids=10de:2188,10de:1aeb,10de:1aec,10de:1aed,1912:0014
